modLoader="javafml"
loaderVersion="[51,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="legendarytooltips"
version="${version}"
displayName="Legendary Tooltips"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/532127"
logoFile="icon.png"
authors="Grend"
description='''Gives rare items a fancy tooltip and adds additional tooltip configuration options.'''

[[dependencies.legendarytooltips]]
	modId="forge"
	mandatory=true
	versionRange="[51,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.2.0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="prism"
	mandatory=true
	versionRange="[1.0.3,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="equipmentcompare"
	mandatory=false
	versionRange="[1.3.0,)"
	ordering="NONE"
	side="BOTH"