modLoader="javafml"
loaderVersion="[1,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="legendarytooltips"
version="${version}"
displayName="Legendary Tooltips"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/532127"
logoFile="icon.png"
authors="Grend"
description='''Gives rare items a fancy tooltip and adds additional tooltip configuration options.'''

[[dependencies.legendarytooltips]]
	modId="neoforge"
	type="required"
	versionRange="[21,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="minecraft"
	type="required"
	versionRange="[1.21,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="iceberg"
	type="required"
	versionRange="[1.2.0,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="prism"
	type="required"
	versionRange="[1.0.8,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="equipmentcompare"
	type="optional"
	versionRange="[1.3.0,)"
	ordering="NONE"
	side="BOTH"

[[mixins]]
	config="legendarytooltips.mixins.json"